export const Actions = {
    SHOW_MODAL: 'SHOW_MODAL',

    ITEM_ADD: 'ITEM_ADD',
    ITEM_REMOVE: 'ITEM_REMOVE',
    ITEMS_CLEAR: 'ITEMS_CLEAR',
    ITEMS_REPLACE: 'ITEMS_REPLACE',

    FOCUS_ITEM_UPDATE: 'FOCUS_ITEM_UPDATE',

    UNDO_RESTORE: 'UNDO_RESTORE',
    UNDO_SAVE_ITEMS: 'UNDO_SAVE_ITEMS',

    // Updating errors for select
    UPDATE_ERRORS: 'UPDATE_ERRORS',
};